version: '3.8'

services:
  backend:
    build:
      context: ./backend/Personal-Finance-Management
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
