version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: @naresh
    ports:
      - "3306:3306"

services:
  backend:
    build:
      context: ./backend/Personal-Finance-Management
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/fms
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
